// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  attackerEntityId: __t.u64().name("attacker_entity_id"),
  defenderEntityId: __t.u64().name("defender_entity_id"),
  combatActionId: __t.i32().name("combat_action_id"),
  damage: __t.i32(),
  isCrit: __t.bool().name("is_crit"),
  isDodge: __t.bool().name("is_dodge"),
});
