// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BarterStallInventoryChangeReason,
  ItemStack,
} from "./types";


export default __t.row({
  shopEntityId: __t.u64().name("shop_entity_id"),
  claimEntityId: __t.u64().name("claim_entity_id"),
  actorEntityId: __t.u64().name("actor_entity_id"),
  get reason() {
    return BarterStallInventoryChangeReason;
  },
  tradeOrderEntityId: __t.option(__t.u64()).name("trade_order_entity_id"),
  tradeAmount: __t.option(__t.i32()).name("trade_amount"),
  get addedItems() {
    return __t.array(ItemStack).name("added_items");
  },
  get removedItems() {
    return __t.array(ItemStack).name("removed_items");
  },
  treasuryCoinsAdded: __t.i32().name("treasury_coins_added"),
  treasuryCoinsRemoved: __t.i32().name("treasury_coins_removed"),
  timestamp: __t.timestamp(),
});
