// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ClaimTreasuryChangeReason,
} from "./types";


export default __t.row({
  claimEntityId: __t.u64().name("claim_entity_id"),
  actorEntityId: __t.u64().name("actor_entity_id"),
  get reason() {
    return ClaimTreasuryChangeReason;
  },
  amount: __t.u32(),
  treasuryAfter: __t.u32().name("treasury_after"),
  timestamp: __t.timestamp(),
});
