// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  actorEntityId: __t.u64().name("actor_entity_id"),
  progressiveActionEntityId: __t.u64().name("progressive_action_entity_id"),
  buildingEntityId: __t.u64().name("building_entity_id"),
  recipeId: __t.i32().name("recipe_id"),
  craftCount: __t.i32().name("craft_count"),
});
