// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  OffsetCoordinatesFloat,
  EnemyType,
} from "./types";


export default __t.row({
  entityId: __t.u64().name("entity_id"),
  get enemyType() {
    return EnemyType.name("enemy_type");
  },
  despawnTimestamp: __t.u64().name("despawn_timestamp"),
  get location() {
    return OffsetCoordinatesFloat;
  },
  get destination() {
    return OffsetCoordinatesFloat;
  },
  movementTimestamp: __t.u64().name("movement_timestamp"),
});
