// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ItemType,
  MarketOrderType,
} from "./types";


export default __t.row({
  claimEntityId: __t.u64().name("claim_entity_id"),
  listingEntityId: __t.u64().name("listing_entity_id"),
  get listingType() {
    return MarketOrderType.name("listing_type");
  },
  buyerEntityId: __t.u64().name("buyer_entity_id"),
  sellerEntityId: __t.u64().name("seller_entity_id"),
  itemId: __t.i32().name("item_id"),
  get itemType() {
    return ItemType.name("item_type");
  },
  quantity: __t.i32(),
  unitPrice: __t.i32().name("unit_price"),
  listingRemainingQuantity: __t.i32().name("listing_remaining_quantity"),
  timestamp: __t.timestamp(),
});
