// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlaceableGrowthOutcome,
  PlaceableGrowthOutcomeV2,
} from "./types";


export default __t.row({
  id: __t.i32().primaryKey(),
  placeableId: __t.i32().name("placeable_id"),
  time: __t.array(__t.f32()),
  get outcomes() {
    return __t.array(PlaceableGrowthOutcome);
  },
  showTimeLeft: __t.bool().name("show_time_left"),
  get outcomesV2() {
    return __t.option(__t.array(PlaceableGrowthOutcomeV2)).name("outcomes_v_2");
  },
});
