// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlayerVoteType,
  PlayerVoteAnswer,
} from "./types";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  get voteType() {
    return PlayerVoteType.name("vote_type");
  },
  initiatorEntityId: __t.u64().name("initiator_entity_id"),
  participantsEntityId: __t.array(__t.u64()).name("participants_entity_id"),
  get answers() {
    return __t.array(PlayerVoteAnswer);
  },
  initiatorName: __t.string().name("initiator_name"),
  passThreshold: __t.f32().name("pass_threshold"),
  get outcome() {
    return PlayerVoteAnswer;
  },
  argument1: __t.u64().name("argument_1"),
  argument2: __t.u64().name("argument_2"),
  outcomeStr: __t.string().name("outcome_str"),
});
