// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SmallHexTileMessage,
} from "./types";


export default __t.row({
  playerEntityId: __t.u64().name("player_entity_id"),
  resourceEntityId: __t.u64().name("resource_entity_id"),
  get location() {
    return SmallHexTileMessage;
  },
  showTimeLeft: __t.bool().name("show_time_left"),
});
