// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  LevelRequirement,
  ItemStack,
  ToolRequirement,
  InputItemStack,
  ExperienceStackF32,
  PlaceableSelfBuffChance,
  PlaceableGrowthOutcomeV2,
} from "./types";


export default __t.row({
  id: __t.i32().primaryKey(),
  verbPhrase: __t.string().name("verb_phrase"),
  placeableId: __t.i32().name("placeable_id"),
  requiredKnowledges: __t.array(__t.i32()).name("required_knowledges"),
  blockingKnowledges: __t.array(__t.i32()).name("blocking_knowledges"),
  get consumedItemStacks() {
    return __t.array(InputItemStack).name("consumed_item_stacks");
  },
  get outputItemStacks() {
    return __t.array(ItemStack).name("output_item_stacks");
  },
  get toolRequirements() {
    return __t.array(ToolRequirement).name("tool_requirements");
  },
  get levelRequirements() {
    return __t.array(LevelRequirement).name("level_requirements");
  },
  get experiencePerProgress() {
    return __t.array(ExperienceStackF32).name("experience_per_progress");
  },
  timeRequirement: __t.f32().name("time_requirement"),
  staminaRequirement: __t.f32().name("stamina_requirement"),
  toolDurabilityLost: __t.i32().name("tool_durability_lost"),
  range: __t.i32(),
  allowUseHands: __t.bool().name("allow_use_hands"),
  powerMultiplier: __t.f32().name("power_multiplier"),
  recipePerformanceId: __t.i32().name("recipe_performance_id"),
  onDestroySpawnedPlaceableId: __t.i32().name("on_destroy_spawned_placeable_id"),
  onDestroySpawnedPlaceableChance: __t.f32().name("on_destroy_spawned_placeable_chance"),
  get onDestroyOutcomes() {
    return __t.option(__t.array(PlaceableGrowthOutcomeV2)).name("on_destroy_outcomes");
  },
  get selfBuffs() {
    return __t.option(__t.array(PlaceableSelfBuffChance)).name("self_buffs");
  },
});
