// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlayerActionLayer,
  PlayerActionType,
  PlayerActionResult,
} from "./types";


export default __t.row({
  autoId: __t.u64().primaryKey().name("auto_id"),
  chunkIndex: __t.u64().name("chunk_index"),
  entityId: __t.u64().name("entity_id"),
  startTime: __t.u64().name("start_time"),
  duration: __t.u64(),
  target: __t.option(__t.u64()),
  recipeId: __t.option(__t.i32()).name("recipe_id"),
  get actionType() {
    return PlayerActionType.name("action_type");
  },
  get layer() {
    return PlayerActionLayer;
  },
  get lastActionResult() {
    return PlayerActionResult.name("last_action_result");
  },
  clientCancel: __t.bool().name("client_cancel"),
  wasConsumed: __t.bool().name("was_consumed"),
  pad1: __t.u8().name("pad_1"),
  pad2: __t.u8().name("pad_2"),
  pad3: __t.u8().name("pad_3"),
});
