import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

test("active region helpers live outside the legacy MainPages bundle", () => {
  const mainPagesUrl = new URL("../src/pages/MainPages.tsx", import.meta.url);
  const mainPages = existsSync(mainPagesUrl) ? readFileSync(mainPagesUrl, "utf8") : "";
  const marketPage = readFileSync(new URL("../src/pages/MarketPage.tsx", import.meta.url), "utf8");
  const server = readFileSync(new URL("../server.mjs", import.meta.url), "utf8");
  const activeRegions = readFileSync(new URL("../src/hooks/useActiveRegions.ts", import.meta.url), "utf8");
  const appShell = readFileSync(new URL("../src/AppShell.tsx", import.meta.url), "utf8");
  const activeRegionsUrl = new URL("../src/hooks/useActiveRegions.ts", import.meta.url);

  assert.equal(existsSync(activeRegionsUrl), true);
  assert.equal(marketPage.includes('import { activeRegionLabel, useActiveRegions } from "../hooks/useActiveRegions";'), true);
  assert.doesNotMatch(mainPages, /type\s+ActiveRegion\s*=/);
  assert.doesNotMatch(mainPages, /function\s+activeRegionLabel\s*\(/);
  assert.doesNotMatch(mainPages, /function\s+useActiveRegions\s*\(/);
  assert.match(activeRegions, /useGameDataGeneration\(String\(claimId \?\? ""\), \["region"\]\)/);
  assert.match(activeRegions, /scopeIdentity.*claimId.*includeRegionId.*scopeKey/);
  assert.match(activeRegions, /current\.scopeIdentity === scopeIdentity/);
  assert.match(activeRegions, /state\.scopeIdentity === scopeIdentity \? state\.regions : \[\]/);
  assert.match(appShell, /monitoredClaimId=\{claimId\}/);
  assert.match(appShell, /activeRegionScopeKey=\{activeRegionScopeKey\}/);
  const routeStart = server.indexOf('url.pathname === "/api/local/regions/active"');
  const routeEnd = server.indexOf('url.pathname === "/api/local/map/catalog"', routeStart);
  const route = server.slice(routeStart, routeEnd);
  assert.match(route, /relayActiveRegions\(\{/);
  assert.match(route, /globalRegionSubscriptionHealth\(\)/);
  assert.doesNotMatch(route, /fetchBitjita|fetchCachedActiveRegions/);
  assert.doesNotMatch(server, /activeRegionsCache|function fetchCachedActiveRegions/);
  assert.match(server, /readSubscriptionHealth\("global", "region"\)/);
  assert.match(server, /const relayGlobalHeartbeatDomains = \["catalogs", "skills", "region"\]/);
  assert.match(server, /for \(const domain of relayGlobalHeartbeatDomains\)/);
  assert.match(server, /recordSubscriptionHealth\(\{/);
  assert.match(server, /function superviseRelayGlobalCatalog\(\)/);
  assert.match(server, /relayGlobalCatalogRuntime\.reconcile\(\{/);
  assert.match(server, /relayReconnectDelayMs\(/);
  assert.match(server, /relayGlobalCatalogSupervisorTimer = setInterval/);
  assert.match(server, /subscription\.state === "connecting"/);
  assert.match(server, /relayGlobalCatalogApplyDeadlineAt = Date\.now\(\) \+ 30_000/);
  assert.match(server, /relayGlobalCatalogLastHealthPersistedAt < 10_000/);
  assert.match(server, /requestRelayRuntimeRefresh\?\.\("manual"\)/);
  assert.match(server, /relayClaimScopeFence\.reconcile\(claimId\)[\s\S]*relayProvider\.reconcile\(providerConfig\(claimId\), currentStateRepository\)/);
  assert.match(server, /relayClaimScopeFence\.run\(claimId,[\s\S]*reconcilePrimaryRegion\(claimId\)/);
});
